export const FETCH_RADIALCHART_REQUEST = "FETCH_RADIALCHART_REQUEST";
export const FETCH_RADIALCHART_SUCCESS = "FETCH_RADIALCHART_SUCCESS";
export const FETCH_RADIALCHART_FAILURE = "FETCH_RADIALCHART_FAILURE";
