export const FETCH_SCATTERPLOT_REQUEST = "FETCH_SCATTERPLOT_REQUEST";
export const FETCH_SCATTERPLOT_SUCCESS = "FETCH_SCATTERPLOT_SUCCESS";
export const FETCH_SCATTERPLOT_FAILURE = "FETCH_SCATTERPLOT_FAILURE";
