export const FETCH_STACKED_MAP_REQUEST = "FETCH_STACKED_MAP_REQUEST";
export const FETCH_STACKED_MAP_SUCCESS = "FETCH_STACKED_MAP_SUCCESS";
export const FETCH_STACKED_MAP_FAILURE = "FETCH_STACKED_MAP_FAILURE";
