export const FETCH_TIMESERIES_MAP_REQUEST = "FETCH_TIMESERIES_MAP_REQUEST";
export const FETCH_TIMESERIES_MAP_SUCCESS = "FETCH_TIMESERIES_MAP_SUCCESS";
export const FETCH_TIMESERIES_MAP_FAILURE = "FETCH_TIMESERIES_MAP_FAILURE";
